title : SGI HD
tagline : pagina de SGI HD
preferences :
  enconding : UTF-8
  
before:
 title : SGI HD
 body : index.html
 
 title : Open a pull request
 description : Open a pull request
 event : pull_request.opened
